# Add configuration values here, as shown below.
#
    # config/application.yml
    
    PUSHER_APP_ID: '1814217'
    PUSHER_KEY: '0dbb39077eb23ebc7d49'
    PUSHER_SECRET: 'cfbe19181746256dc62c'
    PUSHER_CLUSTER: 'ap1'

# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
